### ISSUE TITLE
does not scale well on Expanded Modern Screen XXL

### ISSUE THREAD

**Issue by agentmarine** [BartasRS/Factory_monitoring_screen#3]
![image](https://user-images.githubusercontent.com/3437134/218989684-5149fbb1-3a49-417f-8878-35f02a09fa79.png)
the text doesn't scale particularly well on XXL screens when you have a lot of machines out, in particular covers up the key etc

the text could probably be smaller to help accomodate more machines?

**Comment by BartasRS** [comment]
Hey! Thanks for using my script. 
First thing is this version was made for smaller factories and TBH I did not think how "big" is a typical small cactory in DU :)
Second, all screens in DU have same resolution so the font size used here is the smallest possible for it to still be readable (size 11)
Third, For situations like this please use another [version](https://github.com/BartasRS/Factory-Monitoring-Expanded) of this script meant for 3 screens (or 9). It will be more efficient. If you need any help with customisation I am available in game (IGN Bartas).
